import { StyleSheet } from "react-native";

import { colors } from "@/theme/colors";
import { radius } from "@/theme/radius";
import { spacing } from "@/theme/spacing";

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: colors.background,
  },
  screen: {
    flex: 1,
    backgroundColor: colors.background,
  },
  emptyState: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.background,
  },
  emptyText: {
    color: colors.textPrimary,
    fontSize: 18,
  },
  header: {
    alignItems: "center",
    flexDirection: "row",
    gap: 12,
    paddingBottom: 12,
    paddingHorizontal: spacing.xxl,
    paddingTop: 12,
  },
  iconButton: {
    alignItems: "center",
    backgroundColor: colors.surface,
    borderRadius: radius.lg,
    height: 40,
    justifyContent: "center",
    width: 40,
  },
  dateHeaderTitle: {
    alignItems: "center",
    flex: 1,
    height: 42,
    justifyContent: "center",
    paddingHorizontal: 10,
  },
  headerSquareButton: {
    alignItems: "center",
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: radius.lg,
    borderWidth: StyleSheet.hairlineWidth,
    height: 40,
    justifyContent: "center",
    width: 40,
  },
  headerTitle: {
    color: colors.textPrimary,
    flexShrink: 1,
    fontSize: 17,
    fontWeight: "600",
    letterSpacing: 0,
  },
  autosaveStatusText: {
    color: colors.textMuted,
    fontSize: 11,
    fontWeight: "600",
    letterSpacing: 0,
    marginTop: 1,
  },
  headerActions: {
    alignItems: "center",
    flexDirection: "row",
    gap: 6,
  },
  content: {
    paddingHorizontal: spacing.xxl,
    paddingTop: 8,
  },
  detailsGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
    marginBottom: 14,
  },
  workoutInputWrap: {
    flexGrow: 1,
    minWidth: "47%",
    position: "relative",
  },
  wideInput: {
    minWidth: "100%",
  },
  inputLabel: {
    backgroundColor: colors.background,
    color: colors.textSecondary,
    fontSize: 12,
    left: 12,
    letterSpacing: 0,
    paddingHorizontal: 5,
    position: "absolute",
    top: -8,
    zIndex: 1,
  },
  workoutInput: {
    backgroundColor: "rgba(255,255,255,0.015)",
    borderColor: "rgba(255,255,255,0.14)",
    borderRadius: radius.sm,
    borderWidth: 1,
    color: colors.textPrimary,
    fontSize: 15,
    minHeight: 52,
    paddingHorizontal: 14,
  },
  inputFocused: {
    borderColor: colors.accent,
    borderWidth: 1.5,
  },
  pressableWorkoutInput: {
    alignItems: "center",
    flexDirection: "row",
    gap: 8,
  },
  pressableWorkoutInputText: {
    color: colors.textPrimary,
    flex: 1,
    fontSize: 15,
    fontWeight: "500",
  },
  pressableWorkoutInputIcon: {
    width: 20,
  },
  multilineInput: {
    minHeight: 74,
    paddingTop: 16,
  },
  exerciseList: {
    gap: 6,
  },
  exerciseSection: {
    borderTopColor: "rgba(145, 145, 145, 0.32)",
    borderTopWidth: 0.5,
    paddingBottom: 20,
    paddingTop: 18,
  },
  emptyWorkoutState: {
    alignItems: "center",
    justifyContent: "center",
    minHeight: 260,
    paddingBottom: 24,
  },
  addExerciseFooter: {
    marginBottom: 18,
    marginTop: 18,
  },
  exerciseHeader: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 10,
  },
  exerciseTitle: {
    color: colors.textPrimary,
    flex: 1,
    fontSize: 18,
    fontWeight: "700",
    letterSpacing: 0,
    paddingRight: 12,
  },
  exerciseMenu: {
    alignItems: "center",
    height: 34,
    justifyContent: "center",
    width: 34,
  },
  exerciseNoteInput: {
    backgroundColor: "rgba(255,255,255,0.02)",
    borderColor: "rgba(255,255,255,0.12)",
    borderRadius: radius.sm,
    borderWidth: 1,
    color: colors.textPrimary,
    fontSize: 15,
    lineHeight: 20,
    marginBottom: 12,
    maxHeight: 150,
    minHeight: 48,
    paddingHorizontal: 12,
    paddingTop: 11,
    paddingBottom: 11,
  },
  setHeader: {
    alignItems: "center",
    flexDirection: "row",
    gap: 8,
    marginBottom: 3,
  },
  setHeaderText: {
    color: colors.textMuted,
    fontSize: 12,
    fontWeight: "700",
    letterSpacing: 0,
    textAlign: "left",
    width: 58,
  },
  setNumberLabel: {
    textAlign: "center",
    width: 34,
  },
  notesHeader: {
    flex: 1,
    textAlign: "left",
  },
  removeColumn: {
    width: 24,
  },
  setRowGroup: {
    marginBottom: 8,
  },
  setInputWrap: {
    width: 58,
  },
  notesInputWrap: {
    flex: 1,
    minWidth: 80,
  },
  setRow: {
    alignItems: "flex-start",
    flexDirection: "row",
    gap: 8,
    minHeight: 42,
    paddingVertical: 2,
  },
  setCircle: {
    alignItems: "center",
    backgroundColor: colors.surface,
    borderColor: "rgba(255,255,255,0.82)",
    borderRadius: radius.circle,
    borderWidth: 1,
    height: 32,
    justifyContent: "center",
    marginTop: 3,
    width: 32,
    marginRight: 5,
    marginLeft: -2,
  },
  warmupSetCircle: {
    backgroundColor: "rgba(91, 212, 224, 0.1)",
    borderColor: colors.accent,
  },
  specialSetCircle: {
    backgroundColor: "rgba(91, 212, 224, 0.04)",
    borderColor: colors.accentMuted,
  },
  setCircleText: {
    color: colors.textPrimary,
    fontSize: 13,
    fontWeight: "700",
  },
  warmupSetCircleText: {
    color: colors.accent,
  },
  specialSetCircleText: {
    color: colors.accent,
  },
  setInput: {
    backgroundColor: "rgba(255,255,255,0.02)",
    borderColor: "rgba(255,255,255,0.12)",
    borderRadius: radius.sm,
    borderWidth: 1,
    color: colors.textPrimary,
    fontSize: 15,
    height: 38,
    includeFontPadding: false,
    paddingHorizontal: 8,
    paddingVertical: 0,
    textAlign: "left",
    textAlignVertical: "center",
    width: 58,
  },
  notesInput: {
    color: colors.textPrimary,
    lineHeight: 19,
    maxHeight: 120,
    height: 38,
    minWidth: 80,
    paddingTop: 9,
    paddingBottom: 9,
    textAlign: "left",
    textAlignVertical: "center",
    width: "100%",
  },
  setOptionsButton: {
    alignItems: "center",
    height: 38,
    justifyContent: "center",
    marginTop: 5,
    width: 24,
  },
  exerciseFooter: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 12,
    minHeight: 38,
    paddingTop: 4,
  },
  addSetButton: {
    alignItems: "center",
    alignSelf: "flex-start",
    flexDirection: "row",
    gap: 5,
    minHeight: 36,
    paddingRight: 12,
  },
  addSetText: {
    color: colors.accent,
    fontSize: 15,
    fontWeight: "700",
  },
  exerciseActionGroup: {
    alignItems: "center",
    flexDirection: "row",
    gap: 10,
  },
  exerciseIconButton: {
    alignItems: "center",
    height: 34,
    justifyContent: "center",
    width: 34,
  },
  sheetTitle: {
    color: colors.textPrimary,
    fontSize: 22,
    fontWeight: "600",
    marginBottom: 2,
  },
  sheetDescription: {
    color: colors.textSecondary,
    fontSize: 14,
    lineHeight: 20,
  },
  sheetAction: {
    alignItems: "center",
    flexDirection: "row",
    gap: 16,
    minHeight: 44,
  },
  sheetIcon: {
    width: 34,
  },
  sheetText: {
    color: colors.textPrimary,
    flex: 1,
    fontSize: 17,
    fontWeight: "500",
  },
  sheetTextSelected: {
    color: colors.accent,
  },
  pickerHeader: {
    alignItems: "center",
    flexDirection: "row",
    gap: 12,
    justifyContent: "space-between",
  },
  pickerNavButton: {
    alignItems: "center",
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: radius.md,
    borderWidth: StyleSheet.hairlineWidth,
    height: 40,
    justifyContent: "center",
    width: 40,
  },
  pickerTitle: {
    color: colors.textPrimary,
    flex: 1,
    fontSize: 18,
    fontWeight: "700",
    letterSpacing: 0,
    textAlign: "center",
  },
  weekRow: {
    flexDirection: "row",
    marginTop: 4,
  },
  weekLabel: {
    color: colors.textMuted,
    flex: 1,
    fontSize: 12,
    fontWeight: "700",
    textAlign: "center",
  },
  calendarGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
  },
  calendarCell: {
    alignItems: "center",
    height: 44,
    justifyContent: "center",
    width: "14.285%",
  },
  calendarPill: {
    alignItems: "center",
    borderRadius: radius.md,
    height: 36,
    justifyContent: "center",
    width: 40,
  },
  calendarPillSelected: {
    backgroundColor: colors.accent,
  },
  calendarText: {
    color: colors.textPrimary,
    fontSize: 15,
    fontWeight: "600",
    includeFontPadding: false,
    lineHeight: 18,
    textAlign: "center",
  },
  calendarTextSelected: {
    color: colors.background,
    fontWeight: "800",
  },
  timePicker: {
    alignItems: "center",
    flexDirection: "row",
    gap: 10,
    maxHeight: 230,
  },
  timeColumn: {
    backgroundColor: "rgba(255,255,255,0.02)",
    borderColor: colors.border,
    borderRadius: radius.md,
    borderWidth: StyleSheet.hairlineWidth,
    flex: 1,
    maxHeight: 230,
  },
  timeDivider: {
    color: colors.textPrimary,
    fontSize: 26,
    fontWeight: "700",
  },
  timeOption: {
    alignItems: "center",
    height: 42,
    justifyContent: "center",
  },
  timeOptionSelected: {
    backgroundColor: "rgba(91, 212, 224, 0.16)",
  },
  timeOptionText: {
    color: colors.textPrimary,
    fontSize: 16,
    fontWeight: "600",
  },
  timeOptionTextSelected: {
    color: colors.accent,
  },
  reorderList: {
    paddingHorizontal: spacing.xxl,
    paddingTop: 8,
  },
  reorderRow: {
    alignItems: "center",
    backgroundColor: colors.surface,
    borderRadius: radius.md,
    flexDirection: "row",
    height: 62,
    justifyContent: "space-between",
    marginBottom: 4,
    paddingLeft: 20,
    zIndex: 1,
  },
  reorderRowActive: {
    backgroundColor: colors.surfacePressed,
    borderColor: colors.accent,
    borderWidth: StyleSheet.hairlineWidth,
    elevation: 5,
  },
  reorderRowText: {
    color: colors.textPrimary,
    flex: 1,
    fontSize: 18,
    fontWeight: "500",
    letterSpacing: 0,
  },
  reorderHandle: {
    gap: 4,
    padding: 16,
  },
  reorderHandleLine: {
    backgroundColor: colors.accent,
    borderRadius: radius.xs,
    height: 2,
    width: 24,
  },
  exerciseQuickActions: {
    flexDirection: "row",
    gap: 8,
    marginBottom: 4,
  },
  quickAction: {
    alignItems: "center",
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: radius.md,
    borderWidth: StyleSheet.hairlineWidth,
    flex: 1,
    gap: 8,
    justifyContent: "center",
    minHeight: 76,
    paddingHorizontal: 6,
  },
  quickActionText: {
    color: colors.textPrimary,
    fontSize: 13,
    fontWeight: "700",
    letterSpacing: 0,
    textAlign: "center",
  },
  disabledAction: {
    opacity: 0.52,
  },
  mutedText: {
    color: colors.textMuted,
  },
  deleteText: {
    color: "#ffaaa1",
  },
  pressed: {
    opacity: 0.72,
  },
});

